<?php

/**
 * @file0
 * UUID Condition module.
 *
 * This code is released under the GNU General Public License.
 * This work is Copyright 2016 by Department of Justice and Regulation, Victoria, Australia.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function uuid_condition_form_block_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Add js to set the block visibility config summary.
  $form['#attached']['library'] = array('uuid_condition/drupal.uuid_condition_admin');
}
